package com.linkedin.camus.example.records;  
/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class StringHolder extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"StringHolder\",\"fields\":[{\"name\":\"value\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public StringHolder() {}

  /**
   * All-args constructor.
   */
  public StringHolder(java.lang.CharSequence value) {
    this.value = value;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return value;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: value = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'value' field.
   */
  public java.lang.CharSequence getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.lang.CharSequence value) {
    this.value = value;
  }

  /** Creates a new StringHolder RecordBuilder */
  public static StringHolder.Builder newBuilder() {
    return new StringHolder.Builder();
  }
  
  /** Creates a new StringHolder RecordBuilder by copying an existing Builder */
  public static StringHolder.Builder newBuilder(StringHolder.Builder other) {
    return new StringHolder.Builder(other);
  }
  
  /** Creates a new StringHolder RecordBuilder by copying an existing StringHolder instance */
  public static StringHolder.Builder newBuilder(StringHolder other) {
    return new StringHolder.Builder(other);
  }
  
  /**
   * RecordBuilder for StringHolder instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<StringHolder>
    implements org.apache.avro.data.RecordBuilder<StringHolder> {

    private java.lang.CharSequence value;

    /** Creates a new Builder */
    private Builder() {
      super(StringHolder.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(StringHolder.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.value)) {
        this.value = data().deepCopy(fields()[0].schema(), other.value);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing StringHolder instance */
    private Builder(StringHolder other) {
            super(StringHolder.SCHEMA$);
      if (isValidValue(fields()[0], other.value)) {
        this.value = data().deepCopy(fields()[0].schema(), other.value);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'value' field */
    public java.lang.CharSequence getValue() {
      return value;
    }
    
    /** Sets the value of the 'value' field */
    public StringHolder.Builder setValue(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.value = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'value' field has been set */
    public boolean hasValue() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'value' field */
    public StringHolder.Builder clearValue() {
      value = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public StringHolder build() {
      try {
        StringHolder record = new StringHolder();
        record.value = fieldSetFlags()[0] ? this.value : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
